
   class Barrios {
    private barrios: string[];
   private rubros: string[];

   constructor() {
    this.barrios = [
    "1 de mayo",
    "16 de noviembre",
    "2 de septiembre",
    "20 de junio",
    "23 de abril",
    "4 de febrero",
    "Achaval Peña",
    "Acosta",
    "Aeronáutico",
    "Alberdi",
    "Alberto",
    "Alborada Norte",
    "Alborada Sur",
    "Alejandro Centeno",
    "Almirante Brown",
    "Alta Córdoba",
    "Altamira",
    "Alto Alberdi",
    "Alto Hermoso",
    "Alto Palermo",
    "Alto Verde",
    "Altos de Vélez Sársfield",
    "Altos de Villa Cabrera",
    "Altos San Martín",
    "Altos Sud de San Vicente",
    "Ameghino Norte",
    "Ameghino Sud",
    "Ampliación 1 De Mayo",
    "Ampliación Altamira",
    "Ampliación Benjamin Matienzo",
    "Ampliación Cerveceros",
    "Ampliación Empalme",
    "Ampliación Farina",
    "Ampliación Jardín Espinosa",
    "Ampliación Kennedy",
    "Ampliación Las Palmas",
    "Ampliación Los Plátanos",
    "Ampliación Palmar",
    "Ampliación Panamericano",
    "Ampliación Poeta Lugones",
    "Ampliación Pueyrredon",
    "Ampliación Residencial America",
    "Ampliación Rosedal",
    "Ampliación San Fernando",
    "Ampliación San Pablo",
    "Ampliación Urca",
    "Ampliación Vélez Sarsfield",
    "Ampliación Yapeyu",
    "Ana Maria Zumaran",
    "Apeadero La Tablada",
    "Arcos I",
    "Argüello",
    "Argüello Lourdes",
    "Argüello Norte",
    "Arturo Capdevila",
    "Ate",
    "Autódromo",
    "Avenida",
    "Ayacucho",
    "Bajada De Piedra",
    "Bajada San Roque",
    "Bajo Galan",
    "Bajo General Paz",
    "Bella Vista",
    "Bella Vista Oeste",
    "Betania",
    "Bialet Masse",
    "Boedo",
    "Brigadier San Martín",
    "Cabaña del Pilar",
    "Cabo Farina",
    "Caceres",
    "California",
    "Camino A Villa Posse",
    "Carbo",
    "Carola Lorenzini",
    "Carrara",
    "Caseros",
    "Centro",
    "Centro América",
    "Cerro Chico",
    "Cerro de las Rosas",
    "Cerro Norte",
    "Cerveceros",
    "Chateau Carreras",
    "Ciudadela",
    "Cofico",
    "Colinas de Bella Vista",
    "Colinas de Vélez Sársfield",
    "Colinas del Cerro",
    "Colinas del Cerro Ampliación",
    "Colón",
    "Colonia Lola",
    "Comandante Espora",
    "Comercial",
    "Congreso",
    "Consorcio Esperanza",
    "Cooperativa La Unidad",
    "Córdoba 4",
    "Córdoba 5",
    "Corral de Palos",
    "Country Club",
    "Country Fortín del Pozo",
    "Country Jockey Club",
    "Country Las Delicias",
    "Country Lomas de la Carolina",
    "Cofico",
    "Crisol Norte",
    "Crisol Sud",
    "Cupani",
    "De Los Bioquímicos",
    "Dean Funes",
    "Ducasse",
    "Ejército Argentino",
    "El Cabildo",
    "El Cerrito",
    "El Pueblito",
    "El Quebracho",
    "El Refugio",
    "El Trébol",
    "Emaus",
    "Empalme",
    "Empalme Casas De Obreros Y Empleados",
    "Escobar",
    "Estación Flores",
    "Ferrer",
    "Ferreyra",
    "Ferroviario Mitre",
    "Finca La Dorotea",
    "General Arenales",
    "General Artigas",
    "General Belgrano",
    "General Bustos",
    "General Mosconi",
    "General Paz",
    "General Pueyrredon",
    "General Savio",
    "Granadero Pringles",
    "Granja De Funes",
    "Guarnición Aérea Cba",
    "Guarnición Militar Cba",
    "Guayaquil",
    "Güemes",
    "Guiñazu",
    "Guiñazu Sud",
    "Hipólito Yrigoyen",
    "Hogar Propio",
    "Horizonte",
    "Inaudi",
    "Independencia",
    "Industrial Este",
    "Industrial Oeste",
    "Ipona",
    "Ipv Ituzaingo Anexo",
    "Irupe",
    "Ituzaingo",
    "Ituzaingo Anexo",
    "Jardín",
    "Jardín Del Pilar",
    "Jardín Del Sud",
    "Jardín Espinosa",
    "Jardín Hipódromo",
    "Jeronimo Luis De Cabrera",
    "Jockey Club",
    "José Hernández",
    "José I Rucci",
    "José Ignacio Díaz Sección 1",
    "José Ignacio Diaz Sección 2",
    "José Ignacio Diaz Sección 3",
    "José Ignacio Diaz Sección 4",
    "José Ignacio Diaz Sección 5",
    "Juan B Justo",
    "Juan Xxiii",
    "Juniors",
    "Kairos",
    "Kennedy",
    "La Carolina",
    "La Floresta",
    "La France",
    "La Fraternidad",
    "La Hortensia",
    "La Salle",
    "La Toma",
    "Lamadrid",
    "Las Dalias",
    "Las Delicias",
    "Las Flores",
    "Las Lilas",
    "Las Magnolias",
    "Las Margaritas",
    "Las Palmas",
    "Las Palmas Anexo",
    "Las Playas",
    "Las Rosas",
    "Las Violetas",
    "Liceo General Paz",
    "Lomas De San Martín",
    "Lomas Del Suquia",
    "Los Álamos",
    "Los Ángeles",
    "Los Boulevares",
    "Los Ceibos",
    "Los Eucaliptus",
    "Los Filtros",
    "Los Gigantes",
    "Los Granados",
    "Los Jacarandaes",
    "Los Josefinos",
    "Los Naranjos",
    "Los Olmos",
    "Los Olmos Sud",
    "Los Paraísos",
    "Los Pinos",
    "Los Plátanos",
    "Los Principios",
    "Los Robles",
    "Los Sauces",
    "Maipú Sección 1",
    "Maipú Sección 2",
    "Maldonado",
    "Marcelo T De Alvear",
    "Marcos Sastre",
    "Marechal",
    "Maria Lastenia",
    "Mariano Balcarce",
    "Mariano Fragueiro",
    "Marques Anexo",
    "Marques De Sobremonte",
    "Muller",
    "Maurizi",
    "Mercantil",
    "Militar General Deheza",
    "Mirador",
    "Miralta",
    "Mirizzi",
    "Mitre",
    "Nicolas Avellaneda",
    "Nuestro Hogar I",
    "Nueva Córdoba",
    "Nueva Córdoba Anexa",
    "Nueva Italia",
    "Obrero",
    "Observatorio",
    "Ombu",
    "Oña",
    "OSN",
    "Padre Claret",
    "Palermo Bajo",
    "Palmar",
    "Panamericano",
    "Parque Alameda",
    "Parque Atlantica",
    "Parque Capital",
    "Parque Capital Sud",
    "Parque Chacabuco",
    "Parque Corema",
    "Parque De La Vega Tres",
    "Parque Don Bosco",
    "Parque Futura",
    "Parque Jorge Newbery",
    "Parque Latino",
    "Parque Liceo Sección 1",
    "Parque Liceo Sección 2",
    "Parque Liceo Sección 3",
    "Parque Los Molinos",
    "Parque Modelo",
    "Parque Montecristo",
    "Parque República",
    "Parque San Carlos",
    "Parque San Vicente",
    "Parque Sarmiento",
    "Parque Tablada",
    "Parque Vélez Sarsfield",
    "Paso De Los Andes",
    "Patria",
    "Patricios",
    "Patricios Este",
    "Patricios Norte",
    "Patricios Oeste",
    "Poeta Lugones",
    "Policarpio Cabral",
    "Policial",
    "Portal Del Jacaranda",
    "Posta De Vargas",
    "Primera Junta",
    "Providencia",
    "Puente Blanco",
    "Quebrada De Las Rosas",
    "Quinta Santa Ana",
    "Quintas De Arguello",
    "Quintas De San Jorge",
    "Ramón J Carcano",
    "Recreo Del Norte",
    "Remedios De Escalada",
    "Renacimiento",
    "Rene Favaloro",
    "Residencial America",
    "Residencial Aragón",
    "Residencial Chateau",
    "Residencial Olivos",
    "Residencial San Carlos",
    "Residencial San Jorge",
    "Residencial San Roque",
    "Residencial Santa Ana",
    "Residencial Santa Rosa",
    "Residencial Sud",
    "Residencial Vélez Sarsfield",
    "Rivadavia",
    "Rivera Indarte",
    "Rogelio Martínez",
    "Rosedal",
    "Rosedal Anexo",
    "Sachi",
    "San Antonio",
    "San Cayetano",
    "San Daniel",
    "San Felipe",
    "San Fernando",
    "San Francisco",
    "San Ignacio",
    "San Javier",
    "San José",
    "San Lorenzo",
    "San Lorenzo Norte",
    "San Luis De Francia",
    "San Marcelo",
    "San Martín",
    "San Martín Anexo",
    "San Martín Norte",
    "San Nicolas",
    "San Pablo",
    "San Pedro Nolasco",
    "San Rafael",
    "San Ramón",
    "San Roque",
    "San Salvador",
    "San Vicente",
    "Santa Cecilia",
    "Santa Clara De Asis",
    "Santa Isabel Sección 1",
    "Santa Isabel Sección 2",
    "Santa Isabel Sección 3",
    "Santa Rita",
    "Sargento Cabral",
    "Sarmiento",
    "SEP",
    "SMATA",
    "Suárez",
    "Tablada Park",
    "Talleres Este",
    "Talleres Oeste",
    "Talleres Sud",
    "Tejas Del Sur",
    "Teniente Benjamin Matienzo",
    "Teodoro Felds",
    "Tranviarios",
    "UOCRA",
    "Urca",
    "Uritorco",
    "Urquiza",
    "Valle del Cerro",
    "Vicor",
    "Villa 4 de Agosto",
    "Villa 9 de Julio",
    "Villa Adela",
    "Villa Alberdi",
    "Villa Alicia Risler",
    "Villa Allende Parque",
    "Villa Argentina",
    "Villa Aspacia",
    "Villa Ávalos",
    "Villa Azalais",
    "Villa Azalais Oeste",
    "Villa Belgrano",
    "Villa Bustos",
    "Villa Cabrera",
    "Villa Centenario",
    "Villa Claret",
    "Villa Claudina",
    "Villa Corina",
    "Villa Cornu",
    "Villa Coronel Olmedo",
    "Villa El Libertador",
    "Villa Esquiu",
    "Villa Eucarística",
    "Villa General Urquiza",
    "Villa Gran Parque",
    "Villa Mafekin",
    "Villa Marta",
    "Villa Martínez",
    "Villa Páez",
    "Villa Quisquizacate",
    "Villa Retiro",
    "Villa Revol",
    "Villa Revol Anexo",
    "Villa Rivadavia",
    "Villa Rivera Indarte",
    "Villa Saldan",
    "Villa San Carlos",
    "Villa San Isidro",
    "Villa Serrana",
    "Villa Siburu",
    "Villa Silvano Funes",
    "Villa Solferino",
    "Villa Union",
    "Villa Warcalde",
    "Vivero Norte",
    "Yapeyu",
    "Yofre H",
    "Yofre I",
    "Yofre Norte",
    "Yofre Sud",
    "Zona Rural CPC Ruta 20",
    "Zona Rural CPC Arguello",
    "Zona Rural CPC Rancagua",
    "Zona Rural CPC Colon",
    "Zona Rural CPC Pueyrredon",
    "Zona Rural CPC Libertador",
    "Zona Rural CPC Empalme",
    "Zona Rural CPC Centro América",
    "Zona Rural CPC Monseñor Pablo Cabrera"
    ];
    this.rubros = [
      "MiniSuper",
      "Kiosco",
      "Ferreteria",
      "Panaderia",
      "Carniceria",
      "Verduleria",
      "Farmacia",
      "Restaurante",
      "Peluqueria",  
      "Veterinaria", 
      "Cerrajeria",  
      "Carpinteria",
      "Libreria",
      "Jugueteria",
      "Zapateria",
      "Indumentaria",
      "Articulo de Limpieza",
      "Manicura",
      "Almacen",

    ];
   }
   getRubros() {
    return this.rubros;
    }
   getBarrios() {
    return this.barrios;
   }
  
}
   export default Barrios;
